### ISSUE TITLE
Make database configuration more portable

### ISSUE THREAD

**Issue by subelsky** [ignitebaltimore/ignitespeak#22]
Several people are struggling to get their database configured. It's been a big distraction preventing people from getting into awesome feature development. So I had two ideas. We should probably do both:
- Change the current `database.yml` file to use ERB tags that allow developers to override each value, like so:

``` yaml
development:
  adapter: postgresql
  encoding: unicode
  database: ignitespeak_development
  pool: 5
  username: <%= ENV.fetch("IGNITESPEAK_DB_USERNAME","postgres") %>
  password:
```

With such a change in place, anyone who can't get the database built could just do this:

``` bash
export IGNITESPEAK_DB_USERNAME=my_username
rake db:setup # will connect as DB user "my_username" instead of "postgres"
```
- Setup a docker-type container for the whole project. Since the production app is running on heroku, maybe we can leverage [this project](https://blog.heroku.com/archives/2015/5/5/introducing_heroku_docker_release_build_deploy_heroku_apps_with_docker). That way you should be able to boot up a complete environment for development and testing with one command
